### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by mlocati**
What about adding support to install this package via composer?

All you have to do is:
- customize this `composer.json` file by adding any detail you want (author, homepage, keywords, ...) - see https://getcomposer.org/doc/04-schema.md
- submit `https://github.com/guyasyou/Pure-Cookies-Notice` to [Packagist](https://packagist.org/packages/submit)
- enjoy composer!

For instance, it will be possible to do the following:
```bash
# Create a new concrete5 project
composer create-project concrete5/composer your_project_name

# Enter the project directory
cd your_project_name

# Install concrete5
./concrete/bin/concrete5 c5:install -i

# Download the Pure-Cookies-Notice package
composer require guyasyou/pure_cookies_notice

# Install Pure-Cookies-Notice package in concrete5
./concrete/bin/concrete5 c5:package-install pure_cookies_notice
```

### CODE REVIEW

**Comment by mlocati** [comment]
PS: [here's a package of mine](https://github.com/mlocati/concrete5_vatcode_codicefiscale/) that can be installed with
```bash
composer require mlocati-concrete5-packages/vatcode_codicefiscale
```

**Comment by guyasyou** [comment]
I think it's unnecessary here...

**Comment by mlocati** [comment]
Do you mean that's unnecessary to be able to install your package with composer?

**Comment by guyasyou** [comment]
Yes, who needs it?
I doubt that someone will do the package with this

**Comment by mlocati** [comment]
A lot of people are already doing this: for instance concrete5 has been installed 883 times using composer (see https://packagist.org/packages/concrete5/concrete5)

It's a great way to deploy projects: you don't have to keep copies of every package in a repository: simply running `composer install` or `composer update` let's you install/update packages.

And it doesn't cost you anything: everything is automatic...

**Comment by mlocati** [comment]
Ups, concrete5 has been installed 4477 times using composer (see https://packagist.org/packages/concrete5/core )

**Comment by guyasyou** [comment]
... maybe, i will do it later

**Comment by mlocati** [comment]
Great, thanks!

**Pull request merged**
